[worker]
name = "worker-20-2-1-12"
rpc_server.host = "0.0.0.0"
rpc_server.port = 17891
local_pieces_dir = "/filestore"

[sector_manager]
rpc_client.addr = "/ip4/20.2.1.1/tcp/1789"
rpc_client.headers = { User-Agent = "jsonrpc-core-client" }
piece_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaGstMDEiLCJwZXJtIjoid3JpdGUiLCJleHQiOiIifQ.4zRiU50RuR3hx7nmyR8V_dcZGu596T2x9Xi_iAodmSU"
[sealing]
allowed_miners = [1228105]
allowed_sizes = ["32GiB"]
enable_deals = true
disable_cc = true
max_deals = 100
min_deal_space = "1KiB"
max_retries = 3

[[sealing_thread]]
location = "/sealer/cluster/sealing01"

[[sealing_thread]]
location = "/sealer/cluster/sealing02"

[[sealing_thread]]
location = "/sealer/cluster/sealing03"

[[sealing_thread]]
location = "/sealer/cluster/sealing04"

[[sealing_thread]]
location = "/sealer/cluster/sealing05"

[[sealing_thread]]
location = "/sealer/cluster/sealing06"

[[sealing_thread]]
location = "/sealer/cluster/sealing07"

[[sealing_thread]]
location = "/sealer/cluster/sealing08"

[[sealing_thread]]
location = "/sealer/cluster/sealing09"

[[sealing_thread]]
location = "/sealer/cluster/sealing10"

[[sealing_thread]]
location = "/sealer/cluster/sealing11"

[[sealing_thread]]
location = "/sealer/cluster/sealing12"

[[sealing_thread]]
location = "/sealer/cluster/sealing13"

[[sealing_thread]]
location = "/sealer/cluster/sealing14"

[[sealing_thread]]
location = "/sealer/cluster/sealing15"

[[sealing_thread]]
location = "/sealer/cluster/sealing16"

[[sealing_thread]]
location = "/sealer/cluster/sealing17"

[[sealing_thread]]
location = "/sealer/cluster/sealing18"

[[sealing_thread]]
location = "/sealer/cluster/sealing19"

[[sealing_thread]]
location = "/sealer/cluster/sealing20"

[[sealing_thread]]
location = "/sealer/cluster/sealing21"

[[sealing_thread]]
location = "/sealer/cluster/sealing22"

[[sealing_thread]]
location = "/sealer/cluster/sealing23"

[[sealing_thread]]
location = "/sealer/cluster/sealing24"

[[sealing_thread]]
location = "/sealer/cluster/sealing25"

[[sealing_thread]]
location = "/sealer/cluster/sealing26"

[[sealing_thread]]
location = "/sealer/cluster/sealing27"

[[sealing_thread]]
location = "/sealer/cluster/sealing28"

[[sealing_thread]]
location = "/sealer/cluster/sealing29"

[[sealing_thread]]
location = "/sealer/cluster/sealing30"

 [[sealing_thread]]
location = "/sealer/cluster/sealing31"

 [[sealing_thread]]
location = "/sealer/cluster/sealing32"

 [[sealing_thread]]
location = "/sealer/cluster/sealing33"

 [[sealing_thread]]
location = "/sealer/cluster/sealing34"

 [[sealing_thread]]
location = "/sealer/cluster/sealing35"

 [[sealing_thread]]
location = "/sealer/cluster/sealing36"

 [[sealing_thread]]
location = "/sealer/cluster/sealing37"

 [[sealing_thread]]
location = "/sealer/cluster/sealing38"

 [[sealing_thread]]
location = "/sealer/cluster/sealing39"

 [[sealing_thread]]
location = "/sealer/cluster/sealing40"

 [[sealing_thread]]
location = "/sealer/cluster/sealing41"

 [[sealing_thread]]
location = "/sealer/cluster/sealing42"

 [[sealing_thread]]
location = "/sealer/cluster/sealing43"

 [[sealing_thread]]
location = "/sealer/cluster/sealing44"

 [[sealing_thread]]
location = "/sealer/cluster/sealing45"

 [[sealing_thread]]
location = "/sealer/cluster/sealing46"

 [[sealing_thread]]
location = "/sealer/cluster/sealing47"

 [[sealing_thread]]
location = "/sealer/cluster/sealing48"

 [[sealing_thread]]
location = "/sealer/cluster/sealing49"

 [[sealing_thread]]
location = "/sealer/cluster/sealing50"

 [[sealing_thread]]
location = "/sealer/cluster/sealing51"

 [[sealing_thread]]
location = "/sealer/cluster/sealing52"

 [[sealing_thread]]
location = "/sealer/cluster/sealing53"

 [[sealing_thread]]
location = "/sealer/cluster/sealing54"

[PieceStores]
name = "filestore"
location = "/filestore"
#Plugin = "path/to/objstore-plugin"

[attached]
name = "qn04"
location = "/mnt/qn04"
[attached_selection]
# enable_space_weighted = false

[processors.limitation.concurrent]
add_pieces = 1
tree_d = 1
pc1 = 26
pc2 = 1
c2 = 1
#snap_encode = 1
#snap_prove = 1

[processors.static_tree_d]
32GiB = "/var/tmp/filecoin-proof-parameters/tree_d_all_zero_34359738368"


#[[processors.add_pieces]]
#bin="/root/cluster/add_pieces"

[[processors.tree_d]]
cgroup.cpuset = "11,14,17,20,23,26,50,53,56,59,62,65,68,71,74,77"
concurrent = 10

[[processors.pc1]]
bin="/root/venus-cluster/force-ext-processors"
args = ["processor", "pc1", "--huge_mem_path_32g", "/mnt/huge", "--huge_mem_page_count_32g", "26"]
numa_preferred = 0
cgroup.cpuset = "0-38"
envs = { FORCE_SECTOR_SIZE="34359738368", FIL_PROOFS_HUGEPAGE_START_INDEX="0", FIL_PROOFS_CORE_START_INDEX="0", FIL_PROOFS_USE_MULTICORE_SDR="1", FIL_PROOFS_MULTICORE_SDR_PRODUCERS="1", FORCE_HUGE_PAGE="1" }
concurrent = 13

[[processors.pc1]]
bin="/root/venus-cluster/force-ext-processors"
args = ["processor", "pc1", "--huge_mem_path_32g", "/mnt/huge", "--huge_mem_page_count_32g", "26"]
numa_preferred = 1
cgroup.cpuset = "48-86"
envs = { FORCE_SECTOR_SIZE="34359738368", FIL_PROOFS_HUGEPAGE_START_INDEX="26", FIL_PROOFS_USE_MULTICORE_SDR="1", FIL_PROOFS_MULTICORE_SDR_PRODUCERS="1", FORCE_HUGE_PAGE="1" }
concurrent = 13

[[processors.pc2]]
bin="/root/venus-cluster/force-ext-processors"
args = ["processor", "pc2"]
cgroup.cpuset = "39-47"
concurrent = 1
envs = { FIL_PROOFS_USE_GPU_COLUMN_BUILDER="1", BELLMAN_CUSTOM_GPU='NVIDIA GeForce RTX 3080:8704', FIL_PROOFS_USE_GPU_TREE_BUILDER="1", CUDA_VISIBLE_DEVICES="0",FIL_PROOFS_MAX_GPU_COLUMN_BATCH_SIZE="4000000",FIL_PROOFS_MAX_GPU_TREE_BATCH_SIZE="4000000" }

[[processors.transfer]]
bin = "/root/venus-cluster/force-ext-processors" 
args = ["processor", "qiniu_transfer"]
envs = { QINIU_CACHE_ENABLE="1", QINIU="/root/venus-cluster/qiniu-cfg.toml" }

[[processors.c2]]
bin="/root/venus-cluster/force-ext-processors"
args = ["processor", "c2", "--sector_size", "32GiB"]
cgroup.cpuset = "87-95"
concurrent = 1
envs = { BELLMAN_LOAD_SHM="1", BELLMAN_USE_MAP_BUFFER="1", BELLMAN_CIRCUIT_N="1", BELLMAN_CUSTOM_GPU='NVIDIA GeForce RTX 3080:8704', BELLMAN_PROOF_N="1", CUDA_VISIBLE_DEVICES="1" }
